// static const char main_page[] =
// "<!DOCTYPE html>\n"
// "<html lang=\"ru\">\n"
// "<head>\n"
// "  <meta charset=\"UTF-8\">\n"
// "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
// "  <title>Управление</title>\n"
// "  <style>\n"
// "    body { font-family: -apple-system, sans-serif; text-align: center; padding: 20px; background: #f5f5f7; }\n"
// "    .container { max-width: 500px; margin: 0 auto; }\n"
// "    #value { font-size: 1.8rem; font-weight: bold; color: #0071e3; margin: 30px 0; padding: 16px; background: white; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\n"
// "    .btn { margin: 8px; padding: 12px 24px; font-size: 16px; border: none; border-radius: 8px; cursor: pointer; }\n"
// "    .red { background: #ff3b30; color: white; }\n"
// "    .green { background: #34c759; color: white; }\n"
// "    .blue { background: #0071e3; color: white; }\n"
// "    #status { font-size: 0.9rem; color: #888; margin-top: 10px; }\n"
// "  </style>\n"
// "</head>\n"
// "<body>\n"
// "  <div class=\"container\">\n"
// "    <h2>Данные в реальном времени</h2>\n"
// "    <div id=\"value\">Ожидание данных…</div>\n"
// "    <div id=\"status\"></div>\n"
// "    <button class=\"btn red\" onclick=\"sendCmd('/cmd1')\">Команда 1</button>\n"
// "    <button class=\"btn green\" onclick=\"sendCmd('/cmd2')\">Команда 2</button>\n"
// "    <button class=\"btn blue\" onclick=\"sendCmd('/cmd3')\">Команда 3</button>\n"
// "  </div>\n"
// "\n"
// "  <script>\n"
// "    const valueEl = document.getElementById('value');\n"
// "    const statusEl = document.getElementById('status');\n"
// "\n"
// "    // Подключаемся к SSE-потоку\n"
// "    const evtSource = new EventSource('/sse');\n"
// "\n"
// "    evtSource.onmessage = function(e) {\n"
// "      valueEl.textContent = e.data;\n"
// "      statusEl.textContent = 'Обновлено: ' + new Date().toLocaleTimeString();\n"
// "    };\n"
// "\n"
// "    evtSource.onerror = function() {\n"
// "      valueEl.textContent = '—';\n"
// "      statusEl.textContent = 'Ошибка подключения к данным';\n"
// "      statusEl.style.color = '#ff3b30';\n"
// "      // Попытка переподключения не обязательна на ESP32, но можно добавить\n"
// "    };\n"
// "\n"
// "    function sendCmd(url) {\n"
// "      fetch(url, { method: 'GET' })\n"
// "        .then(r => r.text())\n"
// "        .then(msg => {\n"
// "          console.log('Ответ:', msg);\n"
// "          // Можно показать уведомление, если нужно\n"
// "        })\n"
// "        .catch(err => {\n"
// "          console.error('Ошибка команды:', err);\n"
// "          statusEl.textContent = 'Ошибка команды';\n"
// "          statusEl.style.color = '#ff3b30';\n"
// "        });\n"
// "    }\n"
// "  </script>\n"
// "</body>\n"
// "</html>\n";
static const char main_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
"  <title>ESP32</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"    body {\n"
"      font-family: -apple-system, BlinkMacSystemFont, sans-serif;\n"
"      background: #f0f2f5;\n"
"      min-height: 100vh;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"      padding: 15px;\n"
"    }\n"
"    .container {\n"
"      width: 100%;\n"
"      max-width: 500px;\n"
"      text-align: center;\n"
"    }\n"
"    h1 {\n"
"      font-size: 1.5rem;\n"
"      margin-bottom: 20px;\n"
"      color: #1a1a1a;\n"
"    }\n"
"    #data-display {\n"
"      font-size: 3.5rem;\n"
"      font-weight: bold;\n"
"      color: #0071e3;\n"
"      background: white;\n"
"      padding: 25px 10px;\n"
"      border-radius: 24px;\n"
"      margin: 15px 0 25px;\n"
"      box-shadow: 0 4px 12px rgba(0,0,0,0.08);\n"
"      min-height: 1.2em;\n"
"    }\n"
"    .btn {\n"
"      display: block;\n"
"      width: 100%;\n"
"      padding: 22px 10px;\n"
"      margin: 10px 0;\n"
"      font-size: 20px;\n"
"      font-weight: 600;\n"
"      border: none;\n"
"      border-radius: 20px;\n"
"      cursor: pointer;\n"
"      touch-action: manipulation;\n"
"      -webkit-tap-highlight-color: transparent;\n"
"    }\n"
"    .btn:active {\n"
"      opacity: 0.9;\n"
"      transform: scale(0.98);\n"
"    }\n"
"    .red { background: #ff3b30; color: white; }\n"
"    .green { background: #34c759; color: white; }\n"
"    .blue { background: #0071e3; color: white; }\n"
"    #status {\n"
"      margin-top: 15px;\n"
"      font-size: 1.1rem;\n"
"      font-weight: bold;\n"
"      min-height: 1.5em;\n"
"    }\n"
"    .online { color: #34c759; }\n"
"    .offline { color: #ff3b30; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"container\">\n"
"    <h1>ДАННЫЕ В РЕАЛЬНОМ ВРЕМЕНИ</h1>\n"
"    <div id=\"data-display\">0</div>\n"
"    <button class=\"btn red\" onclick=\"send('cmd1')\">КОМАНДА 1</button>\n"
"    <button class=\"btn green\" onclick=\"send('cmd2')\">КОМАНДА 2</button>\n"
"    <button class=\"btn blue\" onclick=\"send('cmd3')\">КОМАНДА 3</button>\n"
"    <div id=\"status\" class=\"offline\">ПОДКЛЮЧЕНИЕ...</div>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    let ws;\n"
"    const statusEl = document.getElementById('status');\n"
"    const dataEl = document.getElementById('data-display');\n"
"\n"
"    function connect() {\n"
"      ws = new WebSocket('ws://' + location.host + '/ws');\n"
"\n"
"      ws.onopen = () => {\n"
"        statusEl.textContent = 'ГОТОВ';\n"
"        statusEl.className = 'online';\n"
"      };\n"
"\n"
"      ws.onmessage = (event) => {\n"
"        // Обновляем только цифры (игнорируем команды)\n"
"        if (!isNaN(event.data)) {\n"
"          dataEl.textContent = event.data;\n"
"        }\n"
"      };\n"
"\n"
"      ws.onclose = () => {\n"
"        statusEl.textContent = 'ОТКЛЮЧЁН';\n"
"        statusEl.className = 'offline';\n"
"        dataEl.textContent = '—';\n"
"        setTimeout(connect, 2000);\n"
"      };\n"
"    }\n"
"\n"
"    function send(cmd) {\n"
"      if (ws && ws.readyState === WebSocket.OPEN) {\n"
"        ws.send(cmd);\n"
"      }\n"
"    }\n"
"\n"
"    window.onload = connect;\n"
"  </script>\n"
"</body>\n"
"</html>";