
// static const char main_page[] =
// "<!DOCTYPE html>\n"
// "<html>\n"
// "<head>\n"
// "  <meta charset=\"UTF-8\">\n"
// "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
// "  <title>ESP32</title>\n"
// "  <style>\n"
// "    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
// "    body {\n"
// "      font-family: -apple-system, BlinkMacSystemFont, sans-serif;\n"
// "      background: #f0f2f5;\n"
// "      min-height: 100vh;\n"
// "      display: flex;\n"
// "      flex-direction: column;\n"
// "      align-items: center;\n"
// "      justify-content: center;\n"
// "      padding: 15px;\n"
// "    }\n"
// "    .container {\n"
// "      width: 100%;\n"
// "      max-width: 500px;\n"
// "      text-align: center;\n"
// "    }\n"
// "    h1 {\n"
// "      font-size: 1.5rem;\n"
// "      margin-bottom: 20px;\n"
// "      color: #1a1a1a;\n"
// "    }\n"
// "    #data-display {\n"
// "      font-size: 3.5rem;\n"
// "      font-weight: bold;\n"
// "      color: #0071e3;\n"
// "      background: white;\n"
// "      padding: 25px 10px;\n"
// "      border-radius: 24px;\n"
// "      margin: 15px 0 25px;\n"
// "      box-shadow: 0 4px 12px rgba(0,0,0,0.08);\n"
// "      min-height: 1.2em;\n"
// "    }\n"
// "    .btn {\n"
// "      display: block;\n"
// "      width: 100%;\n"
// "      padding: 22px 10px;\n"
// "      margin: 10px 0;\n"
// "      font-size: 20px;\n"
// "      font-weight: 600;\n"
// "      border: none;\n"
// "      border-radius: 20px;\n"
// "      cursor: pointer;\n"
// "      touch-action: manipulation;\n"
// "      -webkit-tap-highlight-color: transparent;\n"
// "    }\n"
// "    .btn:active {\n"
// "      opacity: 0.9;\n"
// "      transform: scale(0.98);\n"
// "    }\n"
// "    .red { background: #ff3b30; color: white; }\n"
// "    .green { background: #34c759; color: white; }\n"
// "    .blue { background: #0071e3; color: white; }\n"
// "    #status {\n"
// "      margin-top: 15px;\n"
// "      font-size: 1.1rem;\n"
// "      font-weight: bold;\n"
// "      min-height: 1.5em;\n"
// "    }\n"
// "    .online { color: #34c759; }\n"
// "    .offline { color: #ff3b30; }\n"
// "  </style>\n"
// "</head>\n"
// "<body>\n"
// "  <div class=\"container\">\n"
// "    <h1>ДАННЫЕ В РЕАЛЬНОМ ВРЕМЕНИ</h1>\n"
// "    <div id=\"data-display\">0</div>\n"
// "    <button class=\"btn red\" onclick=\"send('cmd1')\">КОМАНДА 1</button>\n"
// "    <button class=\"btn green\" onclick=\"send('cmd2')\">КОМАНДА 2</button>\n"
// "    <button class=\"btn blue\" onclick=\"send('cmd3')\">КОМАНДА 3</button>\n"
// "    <div id=\"status\" class=\"offline\">ПОДКЛЮЧЕНИЕ...</div>\n"
// "  </div>\n"
// "\n"
// "  <script>\n"
// "    let ws;\n"
// "    const statusEl = document.getElementById('status');\n"
// "    const dataEl = document.getElementById('data-display');\n"
// "\n"
// "    function connect() {\n"
// "      ws = new WebSocket('ws://' + location.host + '/ws');\n"
// "\n"
// "      ws.onopen = () => {\n"
// "        statusEl.textContent = 'ГОТОВ';\n"
// "        statusEl.className = 'online';\n"
// "      };\n"
// "\n"
// "      ws.onmessage = (event) => {\n"
// "        // Обновляем только цифры (игнорируем команды)\n"
// "        if (!isNaN(event.data)) {\n"
// "          dataEl.textContent = event.data;\n"
// "        }\n"
// "      };\n"
// "\n"
// "      ws.onclose = () => {\n"
// "        statusEl.textContent = 'ОТКЛЮЧЁН';\n"
// "        statusEl.className = 'offline';\n"
// "        dataEl.textContent = '—';\n"
// "        setTimeout(connect, 2000);\n"
// "      };\n"
// "    }\n"
// "\n"
// "    function send(cmd) {\n"
// "      if (ws && ws.readyState === WebSocket.OPEN) {\n"
// "        ws.send(cmd);\n"
// "      }\n"
// "    }\n"
// "\n"
// "    window.onload = connect;\n"
// "  </script>\n"
// "</body>\n"
// "</html>";

static const char main_page[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"UTF-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
"  <title>ESP32</title>\n"
"  <style>\n"
"    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
"    body {\n"
"      font-family: -apple-system, BlinkMacSystemFont, sans-serif;\n"
"      background: #f0f2f5;\n"
"      min-height: 100vh;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      align-items: center;\n"
"      justify-content: center;\n"
"      padding: 15px;\n"
"    }\n"
"    .container {\n"
"      width: 100%;\n"
"      max-width: 500px;\n"
"      text-align: center;\n"
"    }\n"
"    h1 {\n"
"      font-size: 1.5rem;\n"
"      margin-bottom: 20px;\n"
"      color: #1a1a1a;\n"
"    }\n"
"    #data-display {\n"
"      font-size: 3.5rem;\n"
"      font-weight: bold;\n"
"      color: #0071e3;\n"
"      background: white;\n"
"      padding: 25px 10px;\n"
"      border-radius: 24px;\n"
"      margin: 15px 0 25px;\n"
"      box-shadow: 0 4px 12px rgba(0,0,0,0.08);\n"
"      min-height: 1.2em;\n"
"    }\n"
"    .btn-group {\n"
"      display: flex;\n"
"      gap: 10px;\n"
"      margin: 10px 0;\n"
"      justify-content: center;\n"
"    }\n"
"    .btn {\n"
"      flex: 1;\n"
"      padding: 18px 10px;\n"
"      font-size: 18px;\n"
"      font-weight: 600;\n"
"      border: none;\n"
"      border-radius: 16px;\n"
"      cursor: pointer;\n"
"      touch-action: manipulation;\n"
"      -webkit-tap-highlight-color: transparent;\n"
"    }\n"
"    .btn:active {\n"
"      opacity: 0.9;\n"
"      transform: scale(0.98);\n"
"    }\n"
"    .red { background: #ff3b30; color: white; }\n"
"    .green { background: #34c759; color: white; }\n"
"    .blue { background: #0071e3; color: white; }\n"
"    #status {\n"
"      margin-top: 20px;\n"
"      font-size: 1.1rem;\n"
"      font-weight: bold;\n"
"      min-height: 1.5em;\n"
"    }\n"
"    .online { color: #34c759; }\n"
"    .offline { color: #ff3b30; }\n"
"    h3 {\n"
"      font-size: 1.1rem;\n"
"      color: #666;\n"
"      margin: 15px 0 5px 0;\n"
"      font-weight: 500;\n"
"    }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"container\">\n"
"    <h1>ДАННЫЕ В РЕАЛЬНОМ ВРЕМЕНИ</h1>\n"
"    <div id=\"data-display\">0</div>\n"
"    \n"
"    <h3>ГРУППА 1</h3>\n"
"    <div class=\"btn-group\">\n"
"      <button class=\"btn red\" onclick=\"send('cmd1')\">X+</button>\n"
"      <button class=\"btn green\" onclick=\"send('cmd2')\">X-</button>\n"
"      <button class=\"btn blue\" onclick=\"send('cmd3')\">X stop</button>\n"
"    </div>\n"
"    \n"
"    <h3>ГРУППА 2</h3>\n"
"    <div class=\"btn-group\">\n"
"      <button class=\"btn red\" onclick=\"send('cmd4')\">Y+</button>\n"
"      <button class=\"btn green\" onclick=\"send('cmd5')\">Y-</button>\n"
"      <button class=\"btn blue\" onclick=\"send('cmd6')\">Y stop</button>\n"
"    </div>\n"
"    \n"
"    <h3>ГРУППА 3</h3>\n"
"    <div class=\"btn-group\">\n"
"      <button class=\"btn red\" onclick=\"send('cmd7')\">Z+</button>\n"
"      <button class=\"btn green\" onclick=\"send('cmd8')\">Z-</button>\n"
"      <button class=\"btn blue\" onclick=\"send('cmd9')\">Z stop</button>\n"
"    </div>\n"
"    \n"
"    <div id=\"status\" class=\"offline\">ПОДКЛЮЧЕНИЕ...</div>\n"
"  </div>\n"
"\n"
"  <script>\n"
"    let ws;\n"
"    const statusEl = document.getElementById('status');\n"
"    const dataEl = document.getElementById('data-display');\n"
"\n"
"    function connect() {\n"
"      ws = new WebSocket('ws://' + location.host + '/ws');\n"
"\n"
"      ws.onopen = () => {\n"
"        statusEl.textContent = 'ГОТОВ';\n"
"        statusEl.className = 'online';\n"
"      };\n"
"\n"
"      ws.onmessage = (event) => {\n"
"        if (!isNaN(event.data)) {\n"
"          dataEl.textContent = event.data;\n"
"        }\n"
"      };\n"
"\n"
"      ws.onclose = () => {\n"
"        statusEl.textContent = 'ОТКЛЮЧЁН';\n"
"        statusEl.className = 'offline';\n"
"        dataEl.textContent = '—';\n"
"        setTimeout(connect, 2000);\n"
"      };\n"
"    }\n"
"\n"
"    function send(cmd) {\n"
"      if (ws && ws.readyState === WebSocket.OPEN) {\n"
"        ws.send(cmd);\n"
"      }\n"
"    }\n"
"\n"
"    window.onload = connect;\n"
"  </script>\n"
"</body>\n"
"</html>";

